data:
  paths_to_file_root: /data/jjhong96/LundNet_Graph/FourProngV1_MultiClassTrain/data_*.root
  paths_to_file_graphs: /data/jjhong96/LundNet_Graph/FourProngV1_MultiClassTrain/graphs_*_pt

# ROOT tree / branches
tree_name: "FlatSubstructureJetTree"
branch_pt: "fjet_pt"
branch_mass: "fjet_m"
branch_label: "fjet_nProng_labels" # fjet_truth_label, fjet_nProng_labels, fjet_nQuark_labels

# Labels
labels: [1, 2, 3, 4] # This label will be saved in the graphs
label_map: null  # optional mapping, e.g. {1:3, 10:1, 2:2, 12:4} # Move truth_labels to {1,2,3,4} and QCD (10) to 1
# Label mapping happens before the filtering of labels
# label_map: null for no mapping

# Jets per class
n_jets_per_class: 1.5e+6 # Number of jets per class to use (None for all)

# Reweighting
reweight_mode: "flat_pt_mass_2d"  # "none", "flat_pt", "flat_mass", "flat_pt_mass_2d"
pt_range: [350, 2500] # [min, max] in GeV
pt_binN: 100
mass_range: [40, 600] # [min, max] in GeV
mass_binN: 100

# Output
output_dir: "/data/jjhong96/LundNet_Graph/FourProngV1_MultiClassTrain/Shuffled_Graphs_NoHWW_flat_2d/"
histogram_filename: "reweight_histograms.npz"

# Class balancing
reference_label: 1 # Label to use as a reference class for balancing. E.g) I'll scale class 2 sum of weight to match class 1 sum of weight

# Split
test_fraction: 0.1
n_splits_files: 20

random_seed: 42