# Allow to use different label branches, other than the truthLabel
jet_label_branch: 'LRJ_nprong' # LRJ_truthLabel, LRJ_nprong, or LRJ_CapturedQuarkCount
binary_label: false  # if true, use binary classification (signal=1 vs background=0), if false, use multiclass classification(Dump raw signal_jet_label values)

bkg_histos:
  dir_path: &bkg_histos_dir "./histos"
  files: &bkg_histos_files
    FourProngV1/QCD.root: [801169, 801172] # Main background QCD

SS4W:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    560083: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    560084: "./histos/FourProngV1/SS4W.root"
    560085: "./histos/FourProngV1/SS4W.root"
    560086: "./histos/FourProngV1/SS4W.root"
    560087: "./histos/FourProngV1/SS4W.root"
    560088: "./histos/FourProngV1/SS4W.root"
    560089: "./histos/FourProngV1/SS4W.root"
    560090: "./histos/FourProngV1/SS4W.root"
    560091: "./histos/FourProngV1/SS4W.root"
    560092: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [560083, 560084, 560085, 560086, 560087, 560088, 560089, 560090, 560091, 560092] # DSIDs for SS4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: []

SS4W_NoHWW:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    560083: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    560084: "./histos/FourProngV1/SS4W.root"
    560085: "./histos/FourProngV1/SS4W.root"
    560086: "./histos/FourProngV1/SS4W.root"
    560087: "./histos/FourProngV1/SS4W.root"
    560088: "./histos/FourProngV1/SS4W.root"
    560089: "./histos/FourProngV1/SS4W.root"
    560090: "./histos/FourProngV1/SS4W.root"
    560091: "./histos/FourProngV1/SS4W.root"
    560092: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [560084, 560085, 560086, 560087, 560088, 560089, 560090, 560091, 560092] # DSIDs for SS4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [560083] # Skip the HWW* DSID

HHbbWW:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    525952: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    525953: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [525952, 525953] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: []

HHbbWW4TeV:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    525952: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [525952] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [525953]

HHbbWW6TeV:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    525953: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [525953] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [525952]

HSbbWW:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    802061: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    802063: "./histos/FourProngV1/SS4W.root"
    802065: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [802061, 802063, 802065] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [802062, 802064, 802066] # Skip split-boosted signal dsids

HSbbWW2TeV:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    802061: "./histos/FourProngV1/SS4W.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [802061] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [802062, 802063, 802064, 802065, 802066] # Skip split-boosted signal dsids

HSbbWW3TeV:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    802063: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [802063] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [802061, 802062, 802064, 802065, 802066] # Skip split-boosted signal dsids

HSbbWW4TeV:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal: 
    802065: "./histos/FourProngV1/SS4W.root"
  # signal_jet_label: [3, 4]
  signal_jet_label: [4]
  dsids: [802065] # DSIDs for HH4W jets,  keep only jets with nprong label 4
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: [802061, 802062, 802063, 802064, 802066] # Skip split-boosted signal dsids

WZ:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal:
    801859: "./histos/FourProngV1/WZ.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
  signal_jet_label: [2]
  dsids: [801859] # for this DSID, keep only jets with nprong label 2
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: []

TTbar:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal:
    802423: "./histos/FourProngV1/TTbar.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
  signal_jet_label: [3]
  dsids: [802423] # for this DSID, keep only jets with nprong label 3
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: []

QCD:
  pt_hist_files_bkg:
    dir_path: *bkg_histos_dir
    files: *bkg_histos_files
  pt_hist_files_signal:
    801169: "./histos/FourProngV1/QCD.root" # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    801170: "./histos/FourProngV1/QCD.root"
    801171: "./histos/FourProngV1/QCD.root"
    801172: "./histos/FourProngV1/QCD.root"
  signal_jet_label: [1]
  dsids: [801169, 801170, 801171, 801172] # DSIDs for QCD jets, keep only jets with nprong label 1
  pt_range: [350, 3100]   # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 800]  # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3          # minimum number of splittings, or emissions, that jets must have
  skip_dsids: []