bkg_histos:
  # default directory and files for background histograms,
  # can be overriden for each signal type
  dir_path: &bkg_histos_dir "./histos/mass_40-300_pt_200-3100"

  # minimum and maximum DSID each histogram file corresponds to
  files: &bkg_histos_files
    qcdP8.root: [364700, 364712]
    qcdSL.root: [364686, 364694]
    qcdSC.root: [364677, 364685]
    qcdHD.root: [364902, 364909]

top:
  pt_hist_files_bkg:              # TODO: make sure to use histograms with matching mass cut
    dir_path: "./histos/mass_40-3500_pt_350-3100"
    files: *bkg_histos_files
  pt_hist_files_signal:           # pT histograms files for each DSID
    # TODO: maybe the list of DSIDs can now be removed, since you can just take the keys of the pt_hist_files_signal dict
    # TODO: make sure to use histograms with matching mass cutor change the mass cut here
    801661: "./histos/topBSMP8.root" # TODO: fix this histogram, wrong mass and pT ranges
    426345: "./histos/mass_40-3500_pt_350-3100/topBSMP8_426345.root"
  signal_jet_label: [1]
  dsids: [801661, 426345]         # for these DSIDs, keep only jets with truth label 1, and for other samples, keep the QCD jets (with truth label 10)
  pt_range: [350, 3100]           # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, .inf]          # jet mass selection in GeV, for no upper limit use .inf
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3                   # minimum number of splittings, or emissions, that jets must have
  skip_dsids:
  - 364700  # don't lose time with jets that don't pass pt cut
  - 364701  # don't lose time with jets that don't pass pt cut
  - 364702  # don't lose time with jets that don't pass pt cut
  - 801859  # don't keep W jets

W:
  pt_hist_files_bkg:
    dir_path: "./histos/mass_40-300_pt_200-3100"
    files: *bkg_histos_files
  pt_hist_files_signal:           # pT histograms files for each DSID
    801859: "./histos/mass_40-300_pt_200-3100/WBSMP8.root"
    802017: "./histos/mass_40-300_pt_200-3100/WBSMP8_flat.root"
    700843: "./histos/mass_40-300_pt_200-3100/WBSMP8.root"
  # TODO: no flat-pT histos for Wqq_SM (700843) because it won't be used for flat-pT, modify code so it doesn't require flat-pT histos
  signal_jet_label: [2]
  dsids: [801859, 802017, 700843] # for these DSIDs, keep only jets with truth label 2, and for other samples, keep the QCD jets (with truth label 10)
  pt_range: [200, 3100]           # jet pT selection in GeV, upper limit not really necessary, in testing jets with pt > 3k are not included
  mass_range: [40, 300]           # mass selection in GeV, for no upper limit use .inf; upper limit can help with stability in ANN
  eta_max: 2                      # maximum absolute value of jet pseudorapidity, for no upper limit use .inf
  min_splits: 3                   # minimum number of splittings, or emissions, that jets must have
  skip_dsids:
  - 364700  # don't lose time with jets that don't pass pt cut
  - 364701  # don't lose time with jets that don't pass pt cut
  - 364702  # don't lose time with jets that don't pass pt cut
  - 801661  # don't keep top jets
